on: [push, pull_request]
jobs:
  emulator_test:
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install
        working-directory: functions
      - name: Run all the tests
        working-directory: functions
        run: firebase emulators:exec --project test 'npm test'